---
# tasks file for timezone
- name: Set /etc/localtime
  copy: src=/usr/share/zoneinfo/{{ timezone }}
        dest=/etc/localtime
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Set /etc/timezone
  template: dest=/etc/timezone src=timezone.j2
  notify: update tzdata
