# Collectd Graph Panel - see also https://www.debinux.de/2014/01/systemstatus-mit-collectd-und-collectd-graph-panel/
# Needs Webserver with PHP, which is already available on Volumio
- name: download Collectd Graph Panel
  get_url: url=https://github.com/pommi/CGP/archive/v0.4.1.zip dest=/root/cgp.zip
- name: unzip CGP
  unarchive: src=/root/cgp.zip dest=/var/www/ copy=no owner=www-data group=www-data
- name: cgp symlink
# -> http://volumio.local/cgp/
  file: src=/var/www/CGP-0.4.1 dest=/var/www/cgp state=link
- name: rrdtool
  apt: pkg=rrdtool state=present
