- name: collectd packages
  apt: pkg={{item}} state=present
  with_items:
    - collectd-core
    - librrd4
    - rrdcached

- name: rrdcached config
  # Write to disk every 1' (default 300s, see http://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html)
  lineinfile: dest=/etc/default/rrdcached regexp=OPTS= line='OPTS="-l unix:/var/run/rrdcached.sock -w 60"'
  #service rrdcached restart

- name: collectd config
  copy: src={{item}} dest=/etc/collectd/
  with_items:
  - collectd.conf
  - collection.conf
  #rm -rf /var/lib/collectd/*; service collectd restart

# See also https://www.debinux.de/2014/01/systemstatus-mit-collectd-und-collectd-graph-panel/
- name: download Collectd Graph Panel
  get_url: url=https://github.com/pommi/CGP/archive/v0.4.1.zip dest=/root/cgp.zip
- name: unzip CGP
  unarchive: src=/root/cgp.zip dest=/var/www/ copy=no owner=www-data group=www-data
- name: cgp symlink
  file: src=/var/www/CGP-0.4.1 dest=/var/www/cgp state=link
- name: rrdtool
  apt: pkg=rrdtool state=present
