# wget http://sourceforge.net/projects/volumio/files/Raspberry%20PI/1.4/Volumio1.41PI.zip/download
# unzip Volumio1.41PI.zip
# sudo dd bs=1M if=Volumio1.41PI.img of=/dev/mmcblk0
#
# ssh-copy-id root@volumio # Default password: 'volumio'
#
# ansible-playbook -i hosts volumio.yml

---
- hosts: volumio
  remote_user: root
  gather_facts: False
  roles:
    - volumio
    - lirc-mpc
