- name: collectd packages
  pacman: name={{item}} state=present
  with_items:
    - collectd
    - rrdtool

- name: rrdcached systemd file
  # http://andrwe.org/linux/systemd_file_for_rrdcached
  # systemd file included in package: /usr/lib/systemd/system/rrdcached.service
  copy: src=rrdcached.service dest=/etc/systemd/system/multi-user.target.wants/
  notify: restart rrdcached

- name: /etc/conf.d dir
  file: path=/etc/conf.d state=directory

- name: rrdcached config
  # Default for write to disk interval is 300s - see http://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html)
  template: src=rrdcached.conf dest=/etc/conf.d/rrdcached
  notify: restart rrdcached

- name: collectd configuration file
  template: src=collectd.conf.j2 dest=/etc/collectd.conf backup=yes
  notify: restart collectd

- name: create collectd plugin directory
  file: path={{ plugin_conf_dir }} state=directory

- name: copy configuration files
  template: src={{ item }}.conf.j2 dest={{ plugin_conf_dir }}/{{ item }}.conf
  with_items: collectd_configs 
  notify: restart collectd

# # Collectd Graph Panel - see also https://www.debinux.de/2014/01/systemstatus-mit-collectd-und-collectd-graph-panel/
# - name: download Collectd Graph Panel
#   get_url: url=https://github.com/pommi/CGP/archive/v0.4.1.zip dest=/root/cgp.zip
# - name: unzip CGP
#   unarchive: src=/root/cgp.zip dest=/var/www/ copy=no owner=www-data group=www-data
# - name: cgp symlink
#   file: src=/var/www/CGP-0.4.1 dest=/var/www/cgp state=link
# - name: rrdtool
#   pacman: name=rrdtool state=present
