- name: collectd packages
  apt: pkg={{item}} install_recommends=no state=present
  with_items:
    - collectd-core
    - librrd4
    - rrdcached

- name: rrdcached config
  # Default for write to disk interval is 300s - see http://oss.oetiker.ch/rrdtool/doc/rrdcached.en.html)
  lineinfile: dest=/etc/default/rrdcached regexp=OPTS= line='OPTS="-l unix:/var/run/rrdcached.sock -w {{rrdcached_disk_write_interval}}"'
  notify: restart rrdcached

- name: copy configuration file
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify: restart collectd

- name: create collectd plugin directory
  file: path={{ plugin_conf_dir }} state=directory

- name: copy configuration files
  template: src={{ item }}.conf.j2 dest={{ plugin_conf_dir }}/{{ item }}.conf
  with_items: collectd_configs 
  notify: restart collectd
